### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring:
  profiles.active: develop

---
spring:
  profiles: develop
  session:
    store-type: none
#datasource:
#    url: jdbc:p6spy:mysql://127.0.0.1:3306/crown1?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
#    username: root
#    password: 521
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    hikari:
#      auto-commit: false
#      connection-timeout: 30000
#      idle-timeout: 25000
#      login-timeout: 5
#      max-lifetime: 30000
#      read-only: false
#      validation-timeout: 3000
#      maximum-pool-size: 15
#      minimum-idle: 10
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true
#        useLocalSessionState: true
#        rewriteBatchedStatements: true
#        cacheResultSetMetadata: true
#        cacheServerConfiguration: true
#        elideSetAutoCommits: true
#        maintainTimeStats: false
  datasource:
#    driverClassName: com.mysql.jdbc.Driver
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/feidou
#    url: jdbc:mysql://139.196.46.68:8080/superteam
    #url: jdbc:mysql://139.196.153.24:8080/vehicleunion
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

#  jpa:
#    hibernate:
#      ddl-auto: update # todo: in non-dev environments, comment this out:
#    show-sql: true
  output:
    ansi:
      enabled: ALWAYS
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


logging:
  level:
    org.springframework.web: DEBUG
    io.keyell.easyboot.mapper: DEBUG
    io.keyell.easyboot: DEBUG
  path: /logs

server:
  port: 8081



