#### This is the main way to configure the application (other than annotations).
#### This fils is in Yaml format but you can also do this using the traditional
#### Java properties file.
#
#spring:
#  profiles.active: develop
#
#---
#spring:
#  profiles: develop
#  session:
#    store-type: none
#  thymeleaf:
#      mode: HTML5
#      cache: false
#
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://139.196.46.68:8080/superteam
#    #url: jdbc:mysql://139.196.153.24:8080/vehicleunion
#    username: root
#    password: password
#
#  jpa:
#    hibernate:
#      ddl-auto: update # todo: in non-dev environments, comment this out:
#    show-sql: true
#
#logging:
#  path: /logs
#
#server:
#  port: 8081
#
#
#
